Отрисуй меня полностью (часть 1)
htmlacademy-javascript/841461-keksobooking-24 pull request #5
Opened 2021-10-31 21:16 UTC by Gerda0283

Проверка того. что я делаю не так.

2021-11-04 19:04 UTC, artem-Zrilov requested changes

2021-11-06 10:37 UTC, Gerda0283 commented on js/popup.js
> +    popup.querySelector('.popup__avatar').content = author.avatar;
удалила

2021-11-06 10:38 UTC, Gerda0283 commented on js/popup.js
> +  const getPopupPhotos = function() {
есть!

2021-11-06 10:39 UTC, Gerda0283 commented on js/popup.js
> +    featureListItem.classList.add(('popup__feature --') + feature);
есть

2021-11-08 14:18 UTC, artem-Zrilov commented
Отписал в телеграмме

2021-11-08 18:46 UTC, artem-Zrilov requested changes
у тебя сейчас перебирается весь список

2021-11-08 18:46 UTC, artem-Zrilov commented on js/popup.js
> +  userDialog.appendChild(popupFragment);
в popupFragment ничего не добавлено.

2021-11-08 18:46 UTC, artem-Zrilov commented on js/popup.js
> +    priceContainer.innerHTML = '<span>₽/ночь</span>';
используем textContent

2021-11-08 18:46 UTC, artem-Zrilov commented on js/popup.js
> +  popupList.forEach(({author}) => {
а для чего это? Ты же просто делаешь 1 и тоже со всеми элементами списка. Нужно же просто взять 1 элемент и вывести

2021-11-11 13:29 UTC, merged